[libc++] [test] Rename meta:: to TestMeta:: for OSX
OSX's "/usr/include/ncurses.h" defines a `meta` function, and is (for some reason)
included in "MacOSX11.1.sdk/usr/include/module.modulemap", so that identifier is
off-limits for us to use in anything that compiles with -fmodules.

    libcxx/test/support/type_algorithms.h:16:11: error: redefinition of 'meta' as different kind of symbol
    namespace meta {
              ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include/ncurses.h:603:28: note: previous definition is here
    extern NCURSES_EXPORT(int) meta (WINDOW *,bool);                        /* implemented */
                               ^